name: "Multi Event Pipeline Workflow"

on: 
  push:
    branches: 
      - master
      - test

jobs: 
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: "Running on master/test push"
        run: echo "Running in master/test push"
